version: '3.3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    privileged: true
    command: sh run.sh
    ports:
      - 81:8080
      - 35729:35729
      - 5005:5005
    env_file: .env
    environment:
      - DB_URL=${DB_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}