spring:
  datasource:
    password: admin
    url: jdbc:h2:mem:testdb
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console

swagger:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://estoque-api.henriquebarucco.com.br

server:
  error:
    include-stacktrace: never